spring:
  jpa:
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  flyway:
    locations:
     - classpath:/db/migration
    baseline-on-migrate: true
    table: SCHEMA_HISTORY

  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
#    url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  mail:
    host: smtp.gmail.com
    port: 25
    username: floriandodaj55@gmail.com
    password: Fl0rian_d0daj69
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
  header: Authorization
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  token-validity-in-seconds: 1800

server:
  error:
    include-stacktrace: never