spring:
  jpa:
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  flyway:
    locations:
     - classpath:/db/migration
    baseline-on-migrate: true
    table: SCHEMA_HISTORY

  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    #    url: jdbc:h2:file:~/hr-db
    username: sa
    password:
    driverClassName: org.h2.Driver
