spring:
  h2:
    console:
      path: /h2
      enabled: true
  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  flyway:
    locations:
     - classpath:/db/migration
    baseline-on-migrate: true
    table: SCHEMA_HISTORY


  datasource:
#    url: jdbc:mysql://localhost:3306/DB
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  mail:
    host: smtp.gmail.com
    port: 25
    username: floriandodaj511@gmail.com
    password: Floriflori1234!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  header: Authorization
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  token-validity-in-seconds: 1800

server:
  error:
    include-stacktrace: never
  port: 8080

logging:
  level:
    org.springframework.web: ERROR
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: application.log
startingPto: 20

