CREATE TABLE IF NOT EXISTS `holiday`(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    date DATETIME NOT NULL,
    active BOOLEAN NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT false
)