CREATE TABLE IF NOT EXISTS `role`(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    date_created DATETIME,
    is_deleted BOOLEAN DEFAULT FALSE
)